version: '3.1'

networks:
  user-management:

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: user-management
      POSTGRES_USER: user-management
      POSTGRES_PASSWORD: user-management
    ports:
      - "5432:5432"
    networks:
      - user-management

  redis:
    image: redis
    command: redis-server --requirepass user-management
    ports:
      - '6379:6379'
    networks:
      - user-management

  user.management:
    image: mforest/user-management:1.0.0-SNAPSHOT
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      POSGRES_HOST: postgres
      POSGRES_PORT: 5432
      REDIS__HOST: redis
      REDIS_PORT: 6379
    networks:
      - user-management