version: '3.1'

networks:
  user-management:

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user-management
      POSTGRES_USER: user-management
      POSTGRES_PASSWORD: user-management
    ports:
      - "5432:5432"
    networks:
      - user-management