addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"    % "1.6.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"           % "2.2.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"          % "1.6.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"          % "0.9.0")
