name: Scala CI

on: [push]

jobs:

  build:
    name: Build Code

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: sbt clean compile

  code-quality:
    name: Code quality

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Code Format
      run: sbt scalafmtCheckAll scalastyle
    - name: Code Style
      run: sbt scalastyle

  unit-tests:
    name: Unite tests

    needs: [build, code-quality]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: sbt test

  it-tests:
    name: Unite tests

    needs: [build, code-quality]

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: sbt test

  e2e-tests:
    name: E2e tests

    needs: [build, code-quality]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: End-to-end tests
        run: sbt e2e:test

