name: User Management

on: [push]

jobs:

  build:
    name: Continuous Integration

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: user-management
          POSTGRES_USER: user-management
          POSTGRES_PASSWORD: user-management
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: sbt clean compile
    - name: Check code Format
      run: sbt scalafmtCheckAll
    - name: Check code Style
      run: sbt scalastyle
    - name: Unite tests
      run: sbt coverage test
    - name: Integration tests
      run: sbt coverage it:test
    - name: End to end tests
      run: sbt coverage e2e:test
    - name: Check code coverage
      run: sbt coverageAggregate

