name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Code Format & Style
      run: sbt scalafmtCheckAll scalastyle
    - name: Build
      run: sbt clean compile
    - name: Unit tests
      run: sbt test
    - name: Integration tests
      run: sbt it:test
    - name: End-to-end tests
      run: sbt it:e2e
